<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RatnaBay</AssemblyName>
    <RootNamespace>RatnaBay.Client</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5.1" />
    <PackageReference Include="FontStashSharp.MonoGame" Version="1.5.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RatnaBay.Domain\RatnaBay.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Content\World\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Dialogue\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Quests\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Shops\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\Cinzel\Cinzel-wght.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\Cinzel\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\Cinzel\DESCRIPTION.en_us.html" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSans\NotoSans-wght.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSans\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSans\DESCRIPTION.en_us.html" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSansDevanagari\NotoSansDevanagari-wght.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSansDevanagari\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSansBrahmi\NotoSansBrahmi-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Content\Feasibility\Fonts\NotoSansBrahmi\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
